/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.fhswf.forms;

import de.fhswf.classes.Ansprechpartner;
import de.fhswf.classes.Organisation;
import de.fhswf.database.DataP;
import java.awt.Color;
import java.util.Enumeration;

/**
 *
 * @author Dark
 */
public class AnsprechpartnerWindow extends javax.swing.JFrame {

    MainWindow parent;
    Ansprechpartner ansprechpartner;
    boolean editMode;
    
    /**
     * Creates new form AnsprechpartnerWindow
     */
    public AnsprechpartnerWindow(MainWindow _parent) {
        initComponents();
        setLocationRelativeTo(null);
        parent = _parent;
        editMode = false;
        
        jComboBoxOrganisation.removeAllItems();
        DataP d = new DataP();
        for (Enumeration<Organisation> eo = d.getAllOrganisation().elements(); eo.hasMoreElements();)
        {
            jComboBoxOrganisation.addItem(eo.nextElement().getName());
        }
    }
    
    /**
     * Creates new form AnsprechpartnerWindow
     */
    public AnsprechpartnerWindow(MainWindow _parent, Ansprechpartner _ansprechpartner) {
        initComponents();
        setLocationRelativeTo(null);
        parent = _parent;
        ansprechpartner = _ansprechpartner;
        
        jComboBoxOrganisation.removeAllItems();
        DataP d = new DataP();
        for (Enumeration<Organisation> eo = d.getAllOrganisation().elements(); eo.hasMoreElements();)
        {
            jComboBoxOrganisation.addItem(eo.nextElement().getName());
        }
        
        jTextFieldName.setText(ansprechpartner.getName());
        jTextFieldVorname.setText(ansprechpartner.getVorname());
        jTextFieldEmail.setText(ansprechpartner.getEmail());
        jComboBoxOrganisation.setSelectedItem(ansprechpartner.getOrganisation().getName());
        
        editMode = true;
    }
    
    /**
     * Creates new form AnsprechpartnerWindow
     */
    public AnsprechpartnerWindow() {
        initComponents();
        setLocationRelativeTo(null);
        editMode = false;
        
        jComboBoxOrganisation.removeAllItems();
        DataP d = new DataP();
        for (Enumeration<Organisation> eo = d.getAllOrganisation().elements(); eo.hasMoreElements();)
        {
            jComboBoxOrganisation.addItem(eo.nextElement().getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldVorname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxOrganisation = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jButtonAbbrechen = new javax.swing.JButton();
        jButtonSpeichern = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextFieldName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNameKeyTyped(evt);
            }
        });

        jLabel1.setText("Name");

        jTextFieldVorname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldVornameKeyTyped(evt);
            }
        });

        jLabel2.setText("Vorname");

        jTextFieldEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEmailKeyTyped(evt);
            }
        });

        jLabel3.setText("Email");

        jComboBoxOrganisation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Organisation");

        jButtonAbbrechen.setText("Abbrechen");
        jButtonAbbrechen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbbrechenActionPerformed(evt);
            }
        });

        jButtonSpeichern.setText("Speichern");
        jButtonSpeichern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSpeichernActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxOrganisation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldEmail)
                            .addComponent(jTextFieldVorname)
                            .addComponent(jTextFieldName)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 94, Short.MAX_VALUE)
                        .addComponent(jButtonSpeichern)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAbbrechen)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldVorname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxOrganisation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAbbrechen)
                    .addComponent(jButtonSpeichern))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAbbrechenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbbrechenActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonAbbrechenActionPerformed

    private void jButtonSpeichernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSpeichernActionPerformed
        if (!jTextFieldName.getText().equals("") 
                && !jTextFieldVorname.getText().equals("") 
                && !jTextFieldEmail.getText().equals("") 
                && jTextFieldEmail.getText().matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,4}$"))
        {
            DataP d = new DataP();
            Organisation org = d.getOrganisation(jComboBoxOrganisation.getSelectedItem().toString());
            Ansprechpartner ansp = new Ansprechpartner(jTextFieldName.getText(), jTextFieldVorname.getText(), jTextFieldEmail.getText(), org);
            
            if (editMode) {
                d.updateAnsprechpartner(ansprechpartner.getEmail(), ansp);
            }
            else {
                d.saveNewAnsprechpartner(ansp);
            }
            
            parent.update();
            this.dispose();
        }
        else
        {
            
            Color lightred = new Color(255,102,102);
            
            if (jTextFieldName.getText().equals(""))
            {
                jTextFieldName.setBackground(lightred);
            }
            
            if (jTextFieldVorname.getText().equals(""))
            {
                jTextFieldVorname.setBackground(lightred);
            }
            
            if (jTextFieldEmail.getText().equals("") || !jTextFieldEmail.getText().matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,4}$"))
            {
                jTextFieldEmail.setBackground(lightred);
            }
        }
    }//GEN-LAST:event_jButtonSpeichernActionPerformed

    private void jTextFieldNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNameKeyTyped
        jTextFieldName.setBackground(Color.white);
    }//GEN-LAST:event_jTextFieldNameKeyTyped

    private void jTextFieldVornameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldVornameKeyTyped
        jTextFieldVorname.setBackground(Color.white);
    }//GEN-LAST:event_jTextFieldVornameKeyTyped

    private void jTextFieldEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEmailKeyTyped
        jTextFieldEmail.setBackground(Color.white);
    }//GEN-LAST:event_jTextFieldEmailKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnsprechpartnerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnsprechpartnerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnsprechpartnerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnsprechpartnerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnsprechpartnerWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbbrechen;
    private javax.swing.JButton jButtonSpeichern;
    private javax.swing.JComboBox jComboBoxOrganisation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldVorname;
    // End of variables declaration//GEN-END:variables
}
