/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.fhswf.forms;

import de.fhswf.classes.Organisation;
import de.fhswf.database.DataP;
import java.awt.Color;

/**
 *
 * @author Dark
 */
public class OrganisationWindow extends javax.swing.JFrame {

    MainWindow parent;
    Organisation organisation;
    boolean editMode;
    
    /**
     * Creates new form OrganisationWindow
     */
    public OrganisationWindow(MainWindow _parent) {
        initComponents();
        setLocationRelativeTo(null);
        parent = _parent;
        editMode = false;
    }
    
    /**
     * Creates new form OrganisationWindow
     */
    public OrganisationWindow(MainWindow _parent, Organisation _org) {
        initComponents();
        setLocationRelativeTo(null);
        parent = _parent;
        organisation = _org;
        
        jTextFieldName.setText(organisation.getName());
        jTextFieldAdresse.setText(organisation.getAdresse());
        jTextFieldOrt.setText(organisation.getOrt());
        jTextFieldPostleitzahl.setText(organisation.getPostleitzahl());
        
        editMode = true;
    }
    
    /**
     * Creates new form OrganisationWindow
     */
    public OrganisationWindow() {
        initComponents();
        setLocationRelativeTo(null);
        editMode = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAbbrechen = new javax.swing.JButton();
        jButtonSpeichern = new javax.swing.JButton();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldAdresse = new javax.swing.JTextField();
        jTextFieldOrt = new javax.swing.JTextField();
        jTextFieldPostleitzahl = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonAbbrechen.setText("Abbrechen");
        jButtonAbbrechen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbbrechenActionPerformed(evt);
            }
        });

        jButtonSpeichern.setText("Speichern");
        jButtonSpeichern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSpeichernActionPerformed(evt);
            }
        });

        jTextFieldName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNameKeyTyped(evt);
            }
        });

        jTextFieldAdresse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAdresseKeyTyped(evt);
            }
        });

        jTextFieldOrt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldOrtKeyTyped(evt);
            }
        });

        jTextFieldPostleitzahl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPostleitzahlKeyTyped(evt);
            }
        });

        jLabel1.setText("Name");

        jLabel2.setText("Adresse");

        jLabel3.setText("Ort");

        jLabel4.setText("Postleitzahl");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 107, Short.MAX_VALUE)
                        .addComponent(jButtonSpeichern)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAbbrechen))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPostleitzahl)
                            .addComponent(jTextFieldAdresse)
                            .addComponent(jTextFieldName)
                            .addComponent(jTextFieldOrt))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldOrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPostleitzahl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAbbrechen)
                    .addComponent(jButtonSpeichern))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAbbrechenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbbrechenActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonAbbrechenActionPerformed

    private void jButtonSpeichernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSpeichernActionPerformed
        if (!jTextFieldName.getText().equals("") 
                && !jTextFieldAdresse.getText().equals("")  
                && !jTextFieldOrt.getText().equals("")
                && !jTextFieldPostleitzahl.getText().equals("") 
                && jTextFieldPostleitzahl.getText().matches("^[0-9]{5}$"))
        {
            DataP d = new DataP();
            Organisation org = new Organisation(jTextFieldName.getText(), jTextFieldAdresse.getText(), jTextFieldOrt.getText(), jTextFieldPostleitzahl.getText());
            
            if (editMode) {
                d.updateOrganisation(organisation.getName(), org);
            }
            else {
                d.saveNewOrganisation(org);
            }
            
            parent.update();
            this.dispose();
        }
        else
        {
            
            Color lightred = new Color(255,102,102);
            
            if (jTextFieldName.getText().equals(""))
            {
                jTextFieldName.setBackground(lightred);
            }
            
            if (jTextFieldAdresse.getText().equals(""))
            {
                jTextFieldAdresse.setBackground(lightred);
            }
            
            if (jTextFieldOrt.getText().equals(""))
            {
                jTextFieldOrt.setBackground(lightred);
            }
            
            if (jTextFieldPostleitzahl.getText().equals("") || !jTextFieldPostleitzahl.getText().matches("^[0-9]{5}$"))
            {
                jTextFieldPostleitzahl.setBackground(lightred);
            }
        }
    }//GEN-LAST:event_jButtonSpeichernActionPerformed

    private void jTextFieldNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNameKeyTyped
        jTextFieldName.setBackground(Color.white);
    }//GEN-LAST:event_jTextFieldNameKeyTyped

    private void jTextFieldAdresseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAdresseKeyTyped
        jTextFieldAdresse.setBackground(Color.white);
    }//GEN-LAST:event_jTextFieldAdresseKeyTyped

    private void jTextFieldOrtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldOrtKeyTyped
        jTextFieldOrt.setBackground(Color.white);
    }//GEN-LAST:event_jTextFieldOrtKeyTyped

    private void jTextFieldPostleitzahlKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPostleitzahlKeyTyped
        jTextFieldPostleitzahl.setBackground(Color.white);
    }//GEN-LAST:event_jTextFieldPostleitzahlKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrganisationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrganisationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrganisationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrganisationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrganisationWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbbrechen;
    private javax.swing.JButton jButtonSpeichern;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextFieldAdresse;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldOrt;
    private javax.swing.JTextField jTextFieldPostleitzahl;
    // End of variables declaration//GEN-END:variables
}
