/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.fhswf.forms;

import de.fhswf.classes.Ansprechpartner;
import de.fhswf.classes.Benutzer;
import de.fhswf.classes.Projekt;
import de.fhswf.database.DataP;
import java.awt.Color;
import java.util.Enumeration;
import javax.swing.JOptionPane;

/**
 *
 * @author Dark
 */
public class ProjektWindow extends javax.swing.JFrame {

    MainWindow parent;
    TeilnehmerWindow TeilnehmerW;
    Benutzer[] Benutzer;
    
    /**
     * Creates new form ProjektWindow
     */
    public ProjektWindow(MainWindow _parent) {
        initComponents();
        setLocationRelativeTo(null);
        parent = _parent;
        
        jComboBoxAnsprechpartner.removeAllItems();
        DataP d = new DataP();
        for (Enumeration<Ansprechpartner> eo = d.getAllAnsprechpartner().elements(); eo.hasMoreElements();)
        {
            jComboBoxAnsprechpartner.addItem(eo.nextElement().getEmail());
        }
    }
    
    /**
     * Creates new form ProjektWindow
     */
    public ProjektWindow() {
        initComponents();
        setLocationRelativeTo(null);
        
        jComboBoxAnsprechpartner.removeAllItems();
        DataP d = new DataP();
        for (Enumeration<Ansprechpartner> eo = d.getAllAnsprechpartner().elements(); eo.hasMoreElements();)
        {
            jComboBoxAnsprechpartner.addItem(eo.nextElement().getEmail());
        }
    }
    
    public void SetBenutzer(Benutzer[] _benutzer) {
        Benutzer = _benutzer;
        
        jLabelTeilnehmer.setText(Benutzer[0].getName());
        
        if (Benutzer[1] != null) {
            jLabelTeilnehmer.setText(jLabelTeilnehmer.getText() + ", " + Benutzer[1].getName());
        }
        
        if (Benutzer[2] != null) {
            jLabelTeilnehmer.setText(jLabelTeilnehmer.getText() + ", " + Benutzer[2].getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldTitel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldFach = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaKurzbeschreibung = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaBeschreibung = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaSkizze = new javax.swing.JTextArea();
        jComboBoxAnsprechpartner = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelTeilnehmer = new javax.swing.JLabel();
        jButtonTeilnehmerHinzufuegen = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldVortrag1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldVortrag2 = new javax.swing.JTextField();
        jButtonAbbrechen = new javax.swing.JButton();
        jButtonSpeichern = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(500, 450));

        jLabel1.setText("Titel");

        jTextFieldTitel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTitelKeyTyped(evt);
            }
        });

        jLabel2.setText("Fach");

        jTextFieldFach.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldFachKeyTyped(evt);
            }
        });

        jLabel3.setText("Kurzbeschreibung");

        jTextAreaKurzbeschreibung.setColumns(20);
        jTextAreaKurzbeschreibung.setRows(3);
        jTextAreaKurzbeschreibung.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextAreaKurzbeschreibungKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTextAreaKurzbeschreibung);

        jLabel4.setText("Beschreibung");

        jTextAreaBeschreibung.setColumns(20);
        jTextAreaBeschreibung.setRows(5);
        jTextAreaBeschreibung.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextAreaBeschreibungKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(jTextAreaBeschreibung);

        jLabel5.setText("Skizze");

        jTextAreaSkizze.setColumns(20);
        jTextAreaSkizze.setRows(3);
        jTextAreaSkizze.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextAreaSkizzeKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(jTextAreaSkizze);

        jComboBoxAnsprechpartner.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Ansprechpartner");

        jLabel7.setText("Teilnehmer");

        jButtonTeilnehmerHinzufuegen.setText("Hinzufügen");
        jButtonTeilnehmerHinzufuegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTeilnehmerHinzufuegenActionPerformed(evt);
            }
        });

        jLabel9.setText("Vortrag 1");

        jLabel10.setText("Vortrag 2");

        jButtonAbbrechen.setText("Abbrechen");
        jButtonAbbrechen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbbrechenActionPerformed(evt);
            }
        });

        jButtonSpeichern.setText("Speichern");
        jButtonSpeichern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSpeichernActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldTitel)
                            .addComponent(jTextFieldFach)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3)
                            .addComponent(jComboBoxAnsprechpartner, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTeilnehmer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 349, Short.MAX_VALUE)
                                .addComponent(jButtonTeilnehmerHinzufuegen))
                            .addComponent(jTextFieldVortrag1)
                            .addComponent(jTextFieldVortrag2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSpeichern)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAbbrechen)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldTitel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldFach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxAnsprechpartner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabelTeilnehmer)
                    .addComponent(jButtonTeilnehmerHinzufuegen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldVortrag1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldVortrag2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAbbrechen)
                    .addComponent(jButtonSpeichern))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAbbrechenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbbrechenActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonAbbrechenActionPerformed

    private void jButtonSpeichernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSpeichernActionPerformed
        if (!jTextFieldTitel.getText().equals("") 
                && !jTextFieldFach.getText().equals("")  
                && !jTextAreaKurzbeschreibung.getText().equals("")
                && !jTextAreaBeschreibung.getText().equals("")
                && !jTextAreaSkizze.getText().equals(""))
        {
            if (Benutzer == null) {
                JOptionPane.showMessageDialog(this, "Es muss mindestens ein Teilnehmer hinzugefügt werden.", "Teilnehmer", JOptionPane.ERROR_MESSAGE);
            }
            else {
                DataP d = new DataP();
                Ansprechpartner ansp = d.getAnsprechpartner(jComboBoxAnsprechpartner.getSelectedItem().toString());
                Projekt proj = new Projekt(jTextFieldTitel.getText(), jTextFieldFach.getText(), jTextAreaKurzbeschreibung.getText(), jTextAreaBeschreibung.getText(), jTextAreaSkizze.getText(), ansp, Benutzer, jTextFieldVortrag1.getText(), jTextFieldVortrag2.getText());
                d.saveNewProjekt(proj);
                parent.update();
                this.dispose();
            }
        }
        else
        {
            
            Color lightred = new Color(255,102,102);
            
            if (jTextFieldTitel.getText().equals(""))
            {
                jTextFieldTitel.setBackground(lightred);
            }
            
            if (jTextFieldFach.getText().equals(""))
            {
                jTextFieldFach.setBackground(lightred);
            }
            
            if (jTextAreaKurzbeschreibung.getText().equals(""))
            {
                jTextAreaKurzbeschreibung.setBackground(lightred);
            }
            
            if (jTextAreaBeschreibung.getText().equals(""))
            {
                jTextAreaBeschreibung.setBackground(lightred);
            }
            
            if (jTextAreaSkizze.getText().equals(""))
            {
                jTextAreaSkizze.setBackground(lightred);
            }
        }
    }//GEN-LAST:event_jButtonSpeichernActionPerformed

    private void jTextFieldTitelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTitelKeyTyped
        jTextFieldTitel.setBackground(Color.white);
    }//GEN-LAST:event_jTextFieldTitelKeyTyped

    private void jTextFieldFachKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFachKeyTyped
        jTextFieldFach.setBackground(Color.white);
    }//GEN-LAST:event_jTextFieldFachKeyTyped

    private void jTextAreaKurzbeschreibungKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaKurzbeschreibungKeyTyped
        jTextAreaKurzbeschreibung.setBackground(Color.white);
    }//GEN-LAST:event_jTextAreaKurzbeschreibungKeyTyped

    private void jTextAreaBeschreibungKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaBeschreibungKeyTyped
        jTextAreaBeschreibung.setBackground(Color.white);
    }//GEN-LAST:event_jTextAreaBeschreibungKeyTyped

    private void jTextAreaSkizzeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaSkizzeKeyTyped
        jTextAreaSkizze.setBackground(Color.white);
    }//GEN-LAST:event_jTextAreaSkizzeKeyTyped

    private void jButtonTeilnehmerHinzufuegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTeilnehmerHinzufuegenActionPerformed
        if (TeilnehmerW != null)
        {
            TeilnehmerW.dispose();
        }
        TeilnehmerW = new TeilnehmerWindow(this, Benutzer);
        TeilnehmerW.setVisible(true);
    }//GEN-LAST:event_jButtonTeilnehmerHinzufuegenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjektWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjektWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjektWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjektWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjektWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbbrechen;
    private javax.swing.JButton jButtonSpeichern;
    private javax.swing.JButton jButtonTeilnehmerHinzufuegen;
    private javax.swing.JComboBox jComboBoxAnsprechpartner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelTeilnehmer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaBeschreibung;
    private javax.swing.JTextArea jTextAreaKurzbeschreibung;
    private javax.swing.JTextArea jTextAreaSkizze;
    private javax.swing.JTextField jTextFieldFach;
    private javax.swing.JTextField jTextFieldTitel;
    private javax.swing.JTextField jTextFieldVortrag1;
    private javax.swing.JTextField jTextFieldVortrag2;
    // End of variables declaration//GEN-END:variables
}
